/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSceneImageRouteImport } from './routes/api/scene-image'
import { Route as ApiCompanionRouteImport } from './routes/api/companion'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSceneImageRoute = ApiSceneImageRouteImport.update({
  id: '/api/scene-image',
  path: '/api/scene-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanionRoute = ApiCompanionRouteImport.update({
  id: '/api/companion',
  path: '/api/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/companion': typeof ApiCompanionRoute
  '/api/scene-image': typeof ApiSceneImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/companion': typeof ApiCompanionRoute
  '/api/scene-image': typeof ApiSceneImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/companion': typeof ApiCompanionRoute
  '/api/scene-image': typeof ApiSceneImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/api/companion' | '/api/scene-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/companion' | '/api/scene-image'
  id: '__root__' | '/' | '/api/chat' | '/api/companion' | '/api/scene-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCompanionRoute: typeof ApiCompanionRoute
  ApiSceneImageRoute: typeof ApiSceneImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scene-image': {
      id: '/api/scene-image'
      path: '/api/scene-image'
      fullPath: '/api/scene-image'
      preLoaderRoute: typeof ApiSceneImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companion': {
      id: '/api/companion'
      path: '/api/companion'
      fullPath: '/api/companion'
      preLoaderRoute: typeof ApiCompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCompanionRoute: ApiCompanionRoute,
  ApiSceneImageRoute: ApiSceneImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
